Migrating from Nexmo to Vonage lib
nexmo-community/nexmo-rails-telephone-game-vapi pull request #10
Opened 2020-10-01 05:21 UTC by rafaeelaudibert

Closes #9

2020-10-01 13:10 UTC, martyndavies requested changes
This is a great PR. Please can you take a look at this change.

2020-10-02 13:00 UTC, laurenelee commented
Lorna and I discussed this issue and highlighted what a great PR it was on the stream yesterday!

2020-10-06 05:03 UTC, rafaeelaudibert commented on app/controllers/telephone_controller.rb
> +            VonageClient.save_file(params['recording_url'], 'recording.wav')
Sure! Thanks for noticing it

2020-10-06 05:05 UTC, rafaeelaudibert commented
Just applied the change required, @martyndavies! Thanks for noticing it.

Oh, and thanks for the citing on the livestream @laurenelee!

Going forward after this PR, I think it would make sense to change the name of the repository, dont u folks think?

2020-10-12 09:48 UTC, martyndavies approved these changes

2020-10-12 09:48 UTC, merged